sentinel_linear_search_test: sentinel_linear_search_test.c ../src/sentinel_linear_search/sentinel_linear_search.c 
	g++ -o sentinel_linear_search_test sentinel_linear_search_test.c ../src/sentinel_linear_search/sentinel_linear_search.c -Wno-sizeof-array-argument

better_linear_search_test: better_linear_search_test.c ../src/better_linear_search/better_linear_search.c
	g++ -o better_linear_search_test better_linear_search_test.c ../src/better_linear_search/better_linear_search.c -Wno-sizeof-array-argument

linear_search_test: linear_search_test.c ../src/linear_search/linear_search.c
	g++ -o linear_search_test linear_search_test.c ../src/linear_search/linear_search.c

factorial_test: factorial_test.c ../src/factorial/factorial.c 
	g++ -o factorial_test factorial_test.c ../src/factorial/factorial.c