# search tests

sentinel_linear_search_test: sentinel_linear_search_test.c ../src/sentinel_linear_search/sentinel_linear_search.c 
	g++ -o sentinel_linear_search_test sentinel_linear_search_test.c ../src/sentinel_linear_search/sentinel_linear_search.c -Wno-sizeof-array-argument

better_linear_search_test: better_linear_search_test.c ../src/better_linear_search/better_linear_search.c
	g++ -o better_linear_search_test better_linear_search_test.c ../src/better_linear_search/better_linear_search.c -Wno-sizeof-array-argument

linear_search_test: linear_search_test.c ../src/linear_search/linear_search.c
	g++ -o linear_search_test linear_search_test.c ../src/linear_search/linear_search.c

factorial_test: factorial_test.c ../src/factorial/factorial.c 
	g++ -o factorial_test factorial_test.c ../src/factorial/factorial.c

recursive_linear_search_test: recursive_linear_search_test.c ../src/recursive_linear_search/recursive_linear_search.c
	g++ -o recursive_linear_search_test recursive_linear_search_test.c ../src/recursive_linear_search/recursive_linear_search.c

binary_search_test: binary_search_test.c ../src/binary_search/binary_search.c
	g++ -o binary_search_test binary_search_test.c ../src/binary_search/binary_search.c

recursive_binary_search_test: recursive_binary_search_test.c ../src/recursive_binary_search/recursive_binary_search.c
	g++ -o recursive_binary_search_test recursive_binary_search_test.c ../src/recursive_binary_search/recursive_binary_search.c

# sort tests

selection_sort_test:  selection_sort_test.c ../src/selection_sort/selection_sort.c ../src/utils/utils.c
	g++ -o selection_sort_test selection_sort_test.c ../src/selection_sort/selection_sort.c ../src/utils/utils.c

# utils tests

utils_test: utils_test.c ../src/utils/utils.c
	g++ -o utils_test utils_test.c ../src/utils/utils.c