test: sentinel_linear_search_test.c sentinel_linear_search.c
	g++ -o test sentinel_linear_search_test.c sentinel_linear_search.c -Wno-sizeof-array-argument

compile: main.c sentinel_linear_search.c 
	g++ -o sentinel_linear_search sentinel_linear_search.c main.c -Wno-sizeof-array-argument