test: better_linear_search_test.c better_linear_search.c
	g++ -o test better_linear_search_test.c better_linear_search.c -Wno-sizeof-array-argument

compile: main.c better_linear_search.c -Wno-sizeof-array-argument
	g++ -o better_linear_search better_linear_search.c main.c